name: CMake
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Install Clang 22
        run: |
          wget -qO- https://apt.llvm.org/llvm-snapshot.gpg.key | sudo tee /etc/apt/trusted.gpg.d/llvm.asc
          echo "deb https://apt.llvm.org/noble/ llvm-toolchain-noble-22 main" | sudo tee /etc/apt/sources.list.d/llvm-22.list
          sudo apt-get update
          sudo apt-get install -y clang-22
      - name: Build
        uses: threeal/cmake-action@v2.1.0
        with:
          generator: Ninja
          c-compiler: clang-22
          build-dir: cmake-build
          build-args: --target all
      - name: Test
        uses: threeal/cmake-action@v2.1.0
        with:
          generator: Ninja
          c-compiler: clang-22
          build-dir: cmake-build
          build-args: --target test

